# Site settings
title: Jonathan Stowell's Blog

description: > # this means to ignore newlines until "baseurl:"
  Developer/Architect based in Bristol, UK. Work includes architecting solutions for FundsLibrary and more recently Bud an apprenticeship management platform. All views are my own.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
linkedin_username: jonathanstowell
twitter_username: jonathanstowell
github_username:  jonathanstowell

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

disqus: false
disqus_shortname: ''

# Build settings
markdown: kramdown
